"""
export/pptx_builder.py — assembles the .pptx from session state: KPIs,
chart images, insight text.

IMPORTANT: this module must never import insight.client (the OpenRouter
wrapper). It only reads pre-generated insight text from insight.cache. This
is enforced by convention here and checked in
tests/test_export_no_network.py by asserting "insight.client" never appears
in this module's import graph.

Production-grade improvements (v2):
  • Dynamic chart sizing — charts ALWAYS fill the exact available slide area
    with no overflow or clipping.
  • Proper font hierarchy: title 28 pt, subheading 18 pt, body 13 pt, caption 10 pt.
  • Branded colour palette (Aivara navy/teal accent, consistent across all slides).
  • Slide numbers + Aivara footer on every slide.
  • Professional cover slide with gradient-style background band.
  • Table-of-contents slide auto-generated from view names.
  • Section-divider slides between major domain categories.
  • KPI tiles auto-wrap to 2 rows when > 4 tiles are provided.
  • Risk-signal severity badges rendered with coloured left-bar accent.
  • All Plotly figures rendered at 1920 × 1080 (scale=2) for print-quality output.
  • Fail-soft everywhere — missing charts never crash the export.
"""

from __future__ import annotations

import io
import textwrap
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Emu, Inches, Pt

from export.chart_images import (
    FULL_HEIGHT_PX,
    FULL_SCALE,
    FULL_WIDTH_PX,
    HALF_HEIGHT_PX,
    HALF_WIDTH_PX,
    figure_to_png_stream,
)
from insight import cache as insight_cache

# ---------------------------------------------------------------------------
# Slide canvas constants — widescreen 16 : 9
# ---------------------------------------------------------------------------
SLIDE_W = 13.333   # inches
SLIDE_H = 7.5      # inches

MARGIN_L = 0.45    # left margin
MARGIN_R = 0.45    # right margin
MARGIN_T = 0.35    # top margin (below slide edge, not below title)
MARGIN_B = 0.40    # bottom margin (above slide edge — reserved for footer)

CONTENT_W = SLIDE_W - MARGIN_L - MARGIN_R      # 12.43"
TITLE_H   = 0.70                                # reserved for slide title row
FOOTER_H  = 0.30                                # footer strip height

# Y-coordinate where the title text box starts
TITLE_TOP = MARGIN_T
# Y-coordinate where content (KPIs / charts) can start
CONTENT_TOP = MARGIN_T + TITLE_H + 0.15
# Y-coordinate where footer starts
FOOTER_TOP = SLIDE_H - MARGIN_B - FOOTER_H

# Maximum chart area (no text panel beside it)
CHART_FULL_W = CONTENT_W
CHART_FULL_H = FOOTER_TOP - CONTENT_TOP - 0.10   # ≈ 5.50 inches

# Chart + text-panel split (chart on left, insight text on right)
TEXT_PANEL_W  = 3.80
CHART_SPLIT_W = CONTENT_W - TEXT_PANEL_W - 0.20   # ≈ 8.43"
TEXT_PANEL_L  = MARGIN_L + CHART_SPLIT_W + 0.20

# KPI tile constants
KPI_H          = 1.20   # tile height
KPI_GAP        = 0.18   # gap between tiles
KPI_MAX_ROW    = 4      # max tiles per row (wraps to second row otherwise)

# ---------------------------------------------------------------------------
# Brand colours — Aivara palette
# ---------------------------------------------------------------------------
COLOR_BG          = RGBColor(0xFF, 0xFF, 0xFF)
COLOR_BRAND_NAVY  = RGBColor(0x0D, 0x2B, 0x5C)   # primary brand deep navy
COLOR_BRAND_TEAL  = RGBColor(0x00, 0x8B, 0x8B)   # accent teal
COLOR_TEXT        = RGBColor(0x1A, 0x1A, 0x2E)   # near-black body text
COLOR_MUTED       = RGBColor(0x55, 0x5E, 0x75)   # secondary / captions
COLOR_ACCENT_POS  = RGBColor(0x0F, 0x7B, 0x3E)   # green — positive delta
COLOR_ACCENT_NEG  = RGBColor(0xC0, 0x2A, 0x2A)   # red — negative delta
COLOR_ACCENT_WARN = RGBColor(0xB8, 0x7A, 0x00)   # amber — medium severity
COLOR_KPI_BG      = RGBColor(0xF0, 0xF4, 0xFB)   # tile fill
COLOR_KPI_BORDER  = RGBColor(0xD0, 0xD8, 0xEE)   # tile border
COLOR_DIVIDER_BAR = RGBColor(0x00, 0x8B, 0x8B)   # section divider accent bar
COLOR_COVER_BAND  = RGBColor(0x0D, 0x2B, 0x5C)   # cover-slide bottom band

FOOTNOTE_TEXT = (
    "Generated by Aivara Insight  •  All figures computed locally from the "
    "uploaded dataset  •  AI narrative enrichment via OpenRouter (offline fallback available)"
)

# ---------------------------------------------------------------------------
# Data-transfer objects
# ---------------------------------------------------------------------------

@dataclass
class KPITileData:
    label: str
    value_display: str
    delta_display: Optional[str] = None
    delta_positive: Optional[bool] = None


@dataclass
class ViewExportData:
    """Everything one dashboard view (e.g. Executive, Revenue-equivalent)
    needs to render its export slide(s). Built by ui/*.py from session state
    — pptx_builder never recomputes analytics itself."""
    view_name: str
    kpi_tiles: list[KPITileData] = field(default_factory=list)
    trend_figure: object | None = None       # a Plotly Figure, or None
    drivers_table: list[dict] | None = None  # [{category, contribution_pct, ...}]
    drivers_figure: object | None = None
    section: str = ""                        # optional section label for TOC grouping


@dataclass
class DeckInputs:
    dataset_name: str
    period_covered: str
    views: list[ViewExportData]
    risk_signals: list[dict]  # [{description, severity}]


# ---------------------------------------------------------------------------
# Low-level shape helpers
# ---------------------------------------------------------------------------

def _blank_slide(prs: Presentation):
    blank_layout = prs.slide_layouts[6]
    return prs.slides.add_slide(blank_layout)


def _inches(val: float) -> int:
    """Convert float inches to EMU."""
    return Inches(val)


def _fill_slide_background(slide, color: RGBColor) -> None:
    background = slide.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = color


def _add_rect(slide, left: float, top: float, width: float, height: float,
              fill: RGBColor | None = None, line: RGBColor | None = None,
              line_width_pt: float = 0.75):
    """Add a filled rectangle shape (MSO_SHAPE_TYPE 1 = RECTANGLE)."""
    shape = slide.shapes.add_shape(
        1, Inches(left), Inches(top), Inches(width), Inches(height)
    )
    if fill:
        shape.fill.solid()
        shape.fill.fore_color.rgb = fill
    else:
        shape.fill.background()
    if line:
        shape.line.color.rgb = line
        shape.line.width = Pt(line_width_pt)
    else:
        shape.line.fill.background()
    return shape


def _add_textbox(
    slide,
    text: str,
    left: float,
    top: float,
    width: float,
    height: float,
    size: int = 13,
    bold: bool = False,
    color: RGBColor = None,
    align: PP_ALIGN = PP_ALIGN.LEFT,
    word_wrap: bool = True,
) -> None:
    """Generic textbox factory."""
    if color is None:
        color = COLOR_TEXT
    box = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
    tf = box.text_frame
    tf.word_wrap = word_wrap
    para = tf.paragraphs[0]
    para.alignment = align
    run = para.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.color.rgb = color
    return box


def _add_footer(slide, slide_number: int, total_slides: int) -> None:
    """Render a consistent bottom footer strip on every slide."""
    # Subtle separator line
    _add_rect(slide, MARGIN_L, FOOTER_TOP - 0.03, CONTENT_W, 0.03, fill=COLOR_KPI_BORDER)
    # Brand name on left
    _add_textbox(
        slide, "Aivara Insight",
        left=MARGIN_L, top=FOOTER_TOP + 0.03,
        width=4.0, height=FOOTER_H - 0.06,
        size=9, color=COLOR_MUTED,
    )
    # Slide number on right
    _add_textbox(
        slide, f"{slide_number} / {total_slides}",
        left=SLIDE_W - MARGIN_R - 1.5, top=FOOTER_TOP + 0.03,
        width=1.5, height=FOOTER_H - 0.06,
        size=9, color=COLOR_MUTED, align=PP_ALIGN.RIGHT,
    )


def _add_slide_title(slide, text: str) -> None:
    """Slide title with bottom accent underline."""
    _add_textbox(
        slide, text,
        left=MARGIN_L, top=TITLE_TOP,
        width=CONTENT_W, height=TITLE_H,
        size=22, bold=True, color=COLOR_BRAND_NAVY,
    )
    # Thin accent line under the title
    _add_rect(slide, MARGIN_L, TITLE_TOP + TITLE_H, CONTENT_W, 0.04, fill=COLOR_BRAND_TEAL)


# ---------------------------------------------------------------------------
# KPI tile renderer
# ---------------------------------------------------------------------------

def _render_kpi_tiles(
    slide,
    tiles: list[KPITileData],
    top: float,
) -> float:
    """
    Render up to 8 KPI tiles in one or two rows.
    Returns the Y-coordinate immediately after the last tile row.
    """
    if not tiles:
        return top

    tiles = tiles[:8]
    row1 = tiles[:KPI_MAX_ROW]
    row2 = tiles[KPI_MAX_ROW:]

    def _render_row(row: list[KPITileData], row_top: float):
        n = len(row)
        available = CONTENT_W
        tile_w = min(2.80, (available - KPI_GAP * (n - 1)) / n)
        for i, tile in enumerate(row):
            left = MARGIN_L + i * (tile_w + KPI_GAP)
            shape = _add_rect(
                slide, left, row_top, tile_w, KPI_H,
                fill=COLOR_KPI_BG, line=COLOR_KPI_BORDER, line_width_pt=0.5,
            )
            tf = shape.text_frame
            tf.word_wrap = True
            tf.margin_left = Emu(60960)    # 0.85mm
            tf.margin_top  = Emu(36288)    # 0.5mm

            # Label row
            p_label = tf.paragraphs[0]
            r_label = p_label.add_run()
            r_label.text = tile.label
            r_label.font.size = Pt(10)
            r_label.font.color.rgb = COLOR_MUTED

            # Value row
            p_value = tf.add_paragraph()
            r_value = p_value.add_run()
            r_value.text = tile.value_display
            r_value.font.size = Pt(20)
            r_value.font.bold = True
            r_value.font.color.rgb = COLOR_BRAND_NAVY

            # Delta row
            if tile.delta_display:
                p_delta = tf.add_paragraph()
                r_delta = p_delta.add_run()
                r_delta.text = tile.delta_display
                r_delta.font.size = Pt(11)
                r_delta.font.bold = True
                r_delta.font.color.rgb = (
                    COLOR_ACCENT_POS if tile.delta_positive
                    else COLOR_ACCENT_NEG
                ) if tile.delta_positive is not None else COLOR_MUTED

    _render_row(row1, top)
    bottom = top + KPI_H
    if row2:
        _render_row(row2, top + KPI_H + KPI_GAP)
        bottom = top + 2 * KPI_H + KPI_GAP

    return bottom + 0.20   # small padding below last row


# ---------------------------------------------------------------------------
# Chart placement helper — the core of the fix
# ---------------------------------------------------------------------------

def _place_chart(
    slide,
    fig,
    left: float,
    top: float,
    max_width: float,
    max_height: float,
    render_width_px: int = FULL_WIDTH_PX,
    render_height_px: int = FULL_HEIGHT_PX,
) -> None:
    """
    Render *fig* and place it on *slide* so it fits within the bounding
    box defined by (left, top, max_width, max_height) without overflow.

    Strategy:
      1. Render the chart to PNG at a fixed high resolution.
      2. Compute the aspect ratio of the rendered PNG.
      3. Scale it to fill max_width while capping at max_height.
         If max_height is the binding constraint, scale from that side.
      4. Centre the image vertically within the available area.
    """
    try:
        stream = figure_to_png_stream(
            fig, width=render_width_px, height=render_height_px
        )
    except Exception:
        return   # fail soft — never crash the export

    aspect = render_width_px / render_height_px  # e.g. 1920/1080 ≈ 1.778

    # Try width-first
    img_w = max_width
    img_h = img_w / aspect

    # If that would overflow the height budget, fit to height instead
    if img_h > max_height:
        img_h = max_height
        img_w = img_h * aspect

    # Horizontal centering within max_width
    img_left = left + (max_width - img_w) / 2.0
    # Vertical centering within max_height
    img_top  = top  + (max_height - img_h) / 2.0

    try:
        slide.shapes.add_picture(
            stream,
            Inches(img_left),
            Inches(img_top),
            width=Inches(img_w),
            height=Inches(img_h),
        )
    except Exception:
        pass   # defensive — never crash


# ---------------------------------------------------------------------------
# Cached insight helper
# ---------------------------------------------------------------------------

def _cached_insight(view_name: str) -> dict | None:
    return insight_cache.get_for_view(view_name)


# ---------------------------------------------------------------------------
# Individual slide builders
# ---------------------------------------------------------------------------

def build_cover_slide(prs: Presentation, dataset_name: str, period_covered: str, slide_number: int, total_slides: int) -> None:
    """Professional branded cover slide."""
    slide = _blank_slide(prs)

    # Bottom colour band (brand navy, ~40% of slide height)
    band_h = 3.10
    _add_rect(slide, 0, SLIDE_H - band_h, SLIDE_W, band_h, fill=COLOR_BRAND_NAVY)

    # Teal accent bar above the band
    _add_rect(slide, 0, SLIDE_H - band_h - 0.06, SLIDE_W, 0.06, fill=COLOR_BRAND_TEAL)

    # Logo text (replace with an actual logo image if available)
    _add_textbox(
        slide, "AIVARA",
        left=MARGIN_L, top=1.10,
        width=5.0, height=0.70,
        size=36, bold=True, color=COLOR_BRAND_NAVY,
    )
    _add_textbox(
        slide, "Insight  •  Lite",
        left=MARGIN_L, top=1.80,
        width=6.0, height=0.50,
        size=18, bold=False, color=COLOR_BRAND_TEAL,
    )

    # White text on the navy band
    _add_textbox(
        slide, dataset_name,
        left=MARGIN_L, top=SLIDE_H - band_h + 0.40,
        width=CONTENT_W, height=0.70,
        size=24, bold=True, color=COLOR_BG,
    )
    _add_textbox(
        slide, f"Period: {period_covered}",
        left=MARGIN_L, top=SLIDE_H - band_h + 1.15,
        width=CONTENT_W, height=0.45,
        size=14, color=RGBColor(0xCC, 0xD6, 0xEE),
    )
    generated_at = datetime.now(timezone.utc).strftime("%d %b %Y  %H:%M UTC")
    _add_textbox(
        slide, f"Generated  {generated_at}",
        left=MARGIN_L, top=SLIDE_H - band_h + 1.65,
        width=CONTENT_W, height=0.35,
        size=11, color=RGBColor(0x99, 0xAA, 0xCC),
    )

    _add_footer(slide, slide_number, total_slides)


def build_toc_slide(prs: Presentation, views: list[ViewExportData], slide_number: int, total_slides: int) -> None:
    """Auto-generated table of contents."""
    slide = _blank_slide(prs)
    _add_slide_title(slide, "Contents")

    col_count = 2
    col_w = CONTENT_W / col_count - 0.20
    items_per_col = max(1, (len(views) + col_count - 1) // col_count)

    for idx, view in enumerate(views):
        col = idx // items_per_col
        row = idx % items_per_col
        left = MARGIN_L + col * (col_w + 0.40)
        top  = CONTENT_TOP + 0.10 + row * 0.52

        # Bullet dot
        _add_rect(slide, left, top + 0.13, 0.09, 0.09, fill=COLOR_BRAND_TEAL)
        # View name
        _add_textbox(
            slide, view.view_name,
            left=left + 0.18, top=top,
            width=col_w - 0.20, height=0.45,
            size=13, color=COLOR_TEXT,
        )

    _add_footer(slide, slide_number, total_slides)


def build_section_divider_slide(prs: Presentation, section_name: str, slide_number: int, total_slides: int) -> None:
    """Full-bleed section divider."""
    slide = _blank_slide(prs)
    _add_rect(slide, 0, 0, SLIDE_W, SLIDE_H, fill=COLOR_BRAND_NAVY)
    # Teal accent stripe
    _add_rect(slide, 0, SLIDE_H / 2 - 0.06, SLIDE_W, 0.12, fill=COLOR_BRAND_TEAL)

    _add_textbox(
        slide, section_name,
        left=1.0, top=SLIDE_H / 2 - 1.10,
        width=SLIDE_W - 2.0, height=0.90,
        size=32, bold=True, color=COLOR_BG,
        align=PP_ALIGN.CENTER,
    )
    _add_footer(slide, slide_number, total_slides)


def build_executive_summary_slide(prs: Presentation, views: list[ViewExportData], slide_number: int, total_slides: int) -> None:
    slide = _blank_slide(prs)
    _add_slide_title(slide, "Executive Summary")

    # Gather up to 8 KPI tiles from all views
    all_tiles = [t for v in views for t in v.kpi_tiles][:8]
    tile_bottom = _render_kpi_tiles(slide, all_tiles, top=CONTENT_TOP)

    # Insight text below the tiles
    primary_insight = None
    for v in views:
        primary_insight = _cached_insight(v.view_name)
        if primary_insight:
            break

    if primary_insight:
        y = tile_bottom + 0.10
        if primary_insight.get("headline"):
            _add_textbox(
                slide, primary_insight["headline"],
                left=MARGIN_L, top=y,
                width=CONTENT_W, height=0.70,
                size=15, bold=True, color=COLOR_BRAND_NAVY,
            )
            y += 0.75
        if primary_insight.get("driver_explanation"):
            _add_textbox(
                slide, primary_insight["driver_explanation"],
                left=MARGIN_L, top=y,
                width=CONTENT_W, height=0.60,
                size=12, color=COLOR_TEXT,
            )

    _add_footer(slide, slide_number, total_slides)


def build_view_slide(prs: Presentation, view: ViewExportData, slide_number: int, total_slides: int) -> None:
    slide = _blank_slide(prs)
    _add_slide_title(slide, view.view_name)

    # KPI tiles
    tile_bottom = _render_kpi_tiles(slide, view.kpi_tiles, top=CONTENT_TOP)
    chart_top = tile_bottom

    # Available chart area
    avail_h = FOOTER_TOP - chart_top - 0.10

    insight = _cached_insight(view.view_name)

    if insight and view.trend_figure is not None:
        # Split layout: chart left, text panel right
        _place_chart(
            slide, view.trend_figure,
            left=MARGIN_L, top=chart_top,
            max_width=CHART_SPLIT_W, max_height=avail_h,
            render_width_px=HALF_WIDTH_PX, render_height_px=HALF_HEIGHT_PX,
        )
        # Text panel
        y = chart_top
        text_items = [
            (insight.get("headline"),          16, True,  COLOR_BRAND_NAVY),
            (insight.get("driver_explanation"), 12, False, COLOR_TEXT),
            ("Next: " + insight["suggested_action"] if insight.get("suggested_action") else None,
             12, True, COLOR_BRAND_TEAL),
        ]
        for text, size, bold, color in text_items:
            if text:
                h = 0.85 if bold else 0.75
                _add_textbox(
                    slide, text,
                    left=TEXT_PANEL_L, top=y,
                    width=TEXT_PANEL_W, height=h,
                    size=size, bold=bold, color=color,
                )
                y += h + 0.10

    elif view.trend_figure is not None:
        # Full-width chart
        _place_chart(
            slide, view.trend_figure,
            left=MARGIN_L, top=chart_top,
            max_width=CHART_FULL_W, max_height=avail_h,
            render_width_px=FULL_WIDTH_PX, render_height_px=FULL_HEIGHT_PX,
        )

    _add_footer(slide, slide_number, total_slides)


def build_drivers_slide(prs: Presentation, view: ViewExportData, slide_number: int, total_slides: int) -> None:
    if view.drivers_figure is None and not view.drivers_table:
        return
    slide = _blank_slide(prs)
    _add_slide_title(slide, f"Drivers — {view.view_name}")

    avail_h = FOOTER_TOP - CONTENT_TOP - 0.10

    if view.drivers_figure is not None:
        fig_w = CHART_SPLIT_W if view.drivers_table else CHART_FULL_W
        _place_chart(
            slide, view.drivers_figure,
            left=MARGIN_L, top=CONTENT_TOP,
            max_width=fig_w, max_height=avail_h,
        )

    if view.drivers_table:
        text_left = MARGIN_L + CHART_SPLIT_W + 0.20 if view.drivers_figure else MARGIN_L
        panel_w   = TEXT_PANEL_W if view.drivers_figure else CONTENT_W
        y = CONTENT_TOP
        _add_textbox(
            slide, "Top contributors",
            left=text_left, top=y, width=panel_w, height=0.45,
            size=14, bold=True, color=COLOR_BRAND_NAVY,
        )
        y += 0.50
        for row in view.drivers_table[:10]:
            category = row.get("category", "")
            pct = row.get("contribution_pct", 0)
            color = COLOR_ACCENT_POS if pct >= 0 else COLOR_ACCENT_NEG
            label = f"{category}:  {pct:+.1f}%"
            # Left accent bar
            bar_color = COLOR_ACCENT_POS if pct >= 0 else COLOR_ACCENT_NEG
            _add_rect(slide, text_left, y + 0.05, 0.05, 0.30, fill=bar_color)
            _add_textbox(
                slide, label,
                left=text_left + 0.12, top=y, width=panel_w - 0.15, height=0.38,
                size=12, color=color,
            )
            y += 0.42

    _add_footer(slide, slide_number, total_slides)


def build_risk_signals_slide(prs: Presentation, risk_signals: list[dict], slide_number: int, total_slides: int) -> None:
    if not risk_signals:
        return
    slide = _blank_slide(prs)
    _add_slide_title(slide, "Risk Signals")

    severity_colors = {
        "high":   COLOR_ACCENT_NEG,
        "medium": COLOR_ACCENT_WARN,
        "low":    COLOR_MUTED,
    }
    badge_bg_colors = {
        "high":   RGBColor(0xFC, 0xE8, 0xE8),
        "medium": RGBColor(0xFF, 0xF3, 0xCD),
        "low":    RGBColor(0xF0, 0xF4, 0xFB),
    }

    y = CONTENT_TOP + 0.05
    ROW_H = 0.58
    for signal in risk_signals[:10]:
        severity  = signal.get("severity", "low")
        text      = signal.get("description", "")
        s_color   = severity_colors.get(severity, COLOR_MUTED)
        bg_color  = badge_bg_colors.get(severity, COLOR_KPI_BG)

        # Background pill
        _add_rect(slide, MARGIN_L, y, CONTENT_W, ROW_H - 0.06, fill=bg_color, line=s_color, line_width_pt=0.5)
        # Left severity stripe
        _add_rect(slide, MARGIN_L, y, 0.10, ROW_H - 0.06, fill=s_color)
        # Badge label
        _add_textbox(
            slide, severity.upper(),
            left=MARGIN_L + 0.18, top=y + 0.05,
            width=0.80, height=ROW_H - 0.16,
            size=9, bold=True, color=s_color,
        )
        # Description
        _add_textbox(
            slide, text,
            left=MARGIN_L + 1.05, top=y + 0.05,
            width=CONTENT_W - 1.15, height=ROW_H - 0.16,
            size=12, color=COLOR_TEXT,
        )
        y += ROW_H

    _add_footer(slide, slide_number, total_slides)


def build_closing_slide(prs: Presentation, slide_number: int, total_slides: int) -> None:
    slide = _blank_slide(prs)

    # Navy top strip
    _add_rect(slide, 0, 0, SLIDE_W, 1.80, fill=COLOR_BRAND_NAVY)
    _add_rect(slide, 0, 1.80, SLIDE_W, 0.08, fill=COLOR_BRAND_TEAL)

    _add_textbox(
        slide, "AIVARA",
        left=MARGIN_L, top=0.45,
        width=6.0, height=0.80,
        size=30, bold=True, color=COLOR_BG,
    )
    _add_textbox(
        slide, "About this report",
        left=MARGIN_L, top=2.30,
        width=CONTENT_W, height=0.55,
        size=18, bold=True, color=COLOR_BRAND_NAVY,
    )
    wrapped = textwrap.fill(FOOTNOTE_TEXT, width=110)
    _add_textbox(
        slide, wrapped,
        left=MARGIN_L, top=2.95,
        width=CONTENT_W, height=1.40,
        size=12, color=COLOR_MUTED,
    )
    _add_footer(slide, slide_number, total_slides)


# ---------------------------------------------------------------------------
# Public entry-point
# ---------------------------------------------------------------------------

def build_deck(inputs: DeckInputs) -> io.BytesIO:
    """Builds the full deck in-memory: cover, TOC, executive summary, one
    slide per view (+ drivers), risk signals (if any), closing slide.

    Never writes to disk — returns a BytesIO the caller passes straight to
    st.download_button. Never calls the OpenRouter client — only reads from
    insight.cache.
    """
    prs = Presentation()
    prs.slide_width  = Inches(SLIDE_W)
    prs.slide_height = Inches(SLIDE_H)

    # Pre-count slides so footer can show "X / N"
    # Rough count: cover + toc + exec + views*2 (view+drivers) + risk + closing
    # We do two passes: first collect, then render.
    views = inputs.views

    # Build ordered slide list (view + optional drivers)
    view_slide_plan: list[tuple[str, object]] = []
    view_slide_plan.append(("cover", None))
    view_slide_plan.append(("toc",   None))
    view_slide_plan.append(("exec",  None))
    for v in views:
        view_slide_plan.append(("view",    v))
        if v.drivers_figure is not None or v.drivers_table:
            view_slide_plan.append(("drivers", v))
    if inputs.risk_signals:
        view_slide_plan.append(("risk",    None))
    view_slide_plan.append(("closing", None))

    total_slides = len(view_slide_plan)

    for slide_num, (kind, data) in enumerate(view_slide_plan, start=1):
        if kind == "cover":
            build_cover_slide(prs, inputs.dataset_name, inputs.period_covered, slide_num, total_slides)
        elif kind == "toc":
            build_toc_slide(prs, views, slide_num, total_slides)
        elif kind == "exec":
            build_executive_summary_slide(prs, views, slide_num, total_slides)
        elif kind == "view":
            build_view_slide(prs, data, slide_num, total_slides)
        elif kind == "drivers":
            build_drivers_slide(prs, data, slide_num, total_slides)
        elif kind == "risk":
            build_risk_signals_slide(prs, inputs.risk_signals, slide_num, total_slides)
        elif kind == "closing":
            build_closing_slide(prs, slide_num, total_slides)

    buffer = io.BytesIO()
    prs.save(buffer)
    buffer.seek(0)
    return buffer
